
resources: 
- nginx-deployment.yaml
- nginx-svc.yaml
- namespace.yaml

commonLabels:
  app: nginx01

commonAnnotations:
  app: mydemo-annontation

configMapGenerator:
- name: nginx-config
  env: config.properties