# helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-nginx-02  
spec:
  serviceAccountName: fluxcd-helmrelease-installer
  interval: 30m
  chart:
    spec:
      chart: nginx # no alias, just the chart name
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 12h