apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/exploreinclusionapp
    containerapp.apps.tanzu.vmware.com/class: kubernetes
  name: exploreinclusionapp
spec:
  acceptedServiceBindings:
  - name: postgresql
    types:
    - postgresql
  content:
    buildTimestamp: "2024-10-24T21:56:11Z"
    gitCommit: 8cbdbcdab5544723b717a74611ed7afad7d85fde-dirty
    gitURL: github.com/viktoriousss/explore-inclusion.git
    packageImage: harbor.main.emea.end2end.link/viktorious/exploreinclusionapp@sha256:8a5b28d5e0234c823e78e4b1e0d83de6504439a9b0745768717f0bfef8b64399
    packageRefName: exploreinclusionapp.apps.local
    packageVersion: 20241024.2156.11708
    summary: git:8cbdbcd @ 2024-10-24T21:56:11Z
    version: 20241024.2156.11708
  health:
    maxUnavailableReplicas: 10%
  image: harbor.main.emea.end2end.link/viktorious/exploreinclusionapp:20241024.2156.11708@sha256:7e81cd3161c4b8124d79c2f734ed095c59c0bb1de1b23d8337d4ebca224de381
  nonSecretEnv:
  - name: JAVA_TOOL_OPTIONS
    value: -Dmanagement.endpoint.health.probes.add-additional-paths=true -Dmanagement.health.probes.enabled=true
      -Dserver.port=8080 -Dserver.shutdown.grace-period=24s
  ports:
  - name: main
    port: 8080
  probes:
    liveness:
      httpGet:
        path: /livez
        port: 8080
        scheme: HTTP
    readiness:
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
    startup:
      failureThreshold: 120
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 1
  relatedRefs:
  - for: kubernetes.list-replicas
    kind: Pod
    labelSelector: containerapp.apps.tanzu.vmware.com/app-name=exploreinclusionapp
  - apiGroup: apps
    for: kubernetes.service-binding-target
    kind: Deployment
    name: exploreinclusionapp
  - for: kubernetes.service-target
    kind: Service
    name: exploreinclusionapp
  - for: kubernetes.scale-replicas
    keyPath: .data['values.yml']->[yaml].replicas
    kind: Secret
    name: exploreinclusionapp-values
  - for: kubernetes.scale-resources
    keyPath: .data['values.yml']->[yaml].resources
    kind: Secret
    name: exploreinclusionapp-values
  - for: kubernetes.set-secret-env
    keyPath: .data['values.yml']->[yaml].secretEnv
    kind: Secret
    name: exploreinclusionapp-values
  - apiGroup: packaging.carvel.dev
    for: kubernetes.delete
    kind: PackageInstall
    name: exploreinclusionapp
  - apiGroup: data.packaging.carvel.dev
    for: kubernetes.delete
    kind: Package
    name: exploreinclusionapp.apps.local.20241024.2156.11708
  - for: kubernetes.delete
    kind: Secret
    name: exploreinclusionapp-values
  - for: kubernetes.set-content-hash
    keyPath: .data['values.yml']->[yaml].contentHash
    kind: Secret
    name: exploreinclusionapp-values
  - for: kubernetes.set-content-version
    keyPath: .data['values.yml']->[yaml].contentVersion
    kind: Secret
    name: exploreinclusionapp-values
  resources:
    cpu: 300m
    memory: 1Gi
