# helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
spec:
  serviceAccountName: fluxcd-helmrelease-installer
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: prometheus
      version: '1.3.13'
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 5m
  releaseName: prometheus-release
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  #valuesFrom:
  #  - kind: Secret
  #    name: podinfo-values