resources:
- namespace.yaml
- ../../../base/nginx

namespace: production

namePrefix:
  prod-

nameSuffix:
  -v1

patches:
- path: patch-deployment.yaml
- path: patch-service.yaml
  
configMapGenerator:
- name: nginx-config
  behavior: replace
  env: config.properties