apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
  name: dev-db
  namespace: default
spec:
  alias: dev-db
  serviceRef:
    apiGroup: services.tanzu.vmware.com
    connectorName: main
    kind: PreProvisionedService
    name: dev-postgres2
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
    name: spring-music01