apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres_viktorious
  POSTGRES_USER: viktorious
  POSTGRES_PASSWORD: Nx29syDd1X7ten #just some kind of PSW ;)
